import Html exposing (..)
import Html.Attributes exposing (..)

main =
  div []
    [ ul [id "navigation"]
        [ li [] [a [href "/maze/level0"] [text "Level 0"]]
        , li [] [a [href "/maze/level1"] [text "Level 1"]]
        , li [] [a [href "/maze/level2"] [text "Level 2"]]
        , li [] [a [href "/maze/level3"] [text "Level 3"]]
        , li [] [a [href "/maze/level4"] [text "Level 4"]]
        , li [] [a [href "/maze/random"] [text "Random Maze"]]
        ]
    , div [id "input"]
        [ textarea [] []
        , br [] []
        , select []
            [ option [value "java"] [text "Java 8"]
            , option [value "py"]   [text "Python 2.7"]
            ]
        , button [] [text "Save & Run"]
        , button [] [text "Clear Console"]
        , button [] [text "Reset Code"]
        ]
    , div [id "output"]
        [ div [id "world"]
            [ div [id "finish"] []
            , div [id "robot"] []
            ]
        ]
    , div [id "console"] []
    ]
